# Generated by Django 5.1.1 on 2024-11-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('PhoneNumber', models.CharField(max_length=50)),
                ('Message', models.CharField(max_length=50)),
            ],
        ),
    ]
