# Generated by Django 5.1.1 on 2024-11-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Managements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorcontactmodel',
            name='Email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visitorcontactmodel',
            name='Fullname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visitorcontactmodel',
            name='Message',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visitorcontactmodel',
            name='PhoneNumber',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
