# Generated by Django 5.1.1 on 2024-11-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Managements', '0004_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='category',
            field=models.CharField(choices=[('important', 'Important'), ('event', 'Event'), ('academic', 'Academic'), ('administrative', 'Administrative'), ('scholarship', 'Scholarship'), ('hackathon', 'Hackathon'), ('workshop', 'Workshop'), ('holiday', 'Holiday')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
