# Generated by Django 5.1 on 2024-11-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Managements', '0005_alter_gallery_description_alter_gallery_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Notices/'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='category',
            field=models.CharField(choices=[('important', 'Important'), ('event', 'Event'), ('academic', 'Academic'), ('administrative', 'Administrative'), ('scholarship', 'Scholarship'), ('hackathon', 'Hackathon'), ('workshop', 'Workshop'), ('holiday', 'Holiday')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
